spring.application.name=effectiveMobile
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mysecretpassword}

# liquibase
spring.liquibase.change-log=classpath:db/changelog/db.master_changelog.yaml
spring.liquibase.enabled=true

#spring-security
spring.security.user.name=${SPRING_ADMIN_LOGIN:admin}
spring.security.user.password=${SPRING_ADMIN_PWD:admin}
